name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: timecard
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: timecard
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: timecard
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_name: timecard.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        override: true
    
    - name: Build
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: timecard-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/${{ matrix.binary_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/timecard-x86_64-unknown-linux-gnu/timecard
          artifacts/timecard-x86_64-apple-darwin/timecard
          artifacts/timecard-aarch64-apple-darwin/timecard
          artifacts/timecard-x86_64-pc-windows-msvc/timecard.exe
        tag_name: ${{ github.ref_name }}
        name: TimeCard ${{ github.ref_name }}
        body: |
          TimeCard v${{ github.ref_name }} - Time tracking application with GUI
          
          ## Downloads
          - **Linux (x86_64)**: timecard
          - **macOS Intel**: timecard
          - **macOS Apple Silicon**: timecard
          - **Windows**: timecard.exe
          
          ## Usage
          ```bash
          # CLI mode
          ./timecard --help
          
          # GUI mode
          ./timecard gui
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
